
package view;

import javax.swing.JOptionPane;
import controller.ControleProduto;
import javax.swing.table.DefaultTableModel;
import model.Produto;

import java.util.List;

/**
 *
 * @author sxgame
 */
public class jfCadastro extends javax.swing.JFrame {

    private ControleProduto pro = new ControleProduto();
    private String nomeBusca;

    /**
     * Creates new form jfCadastro
     */
    public jfCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JtfNome = new javax.swing.JTextField();
        JtfPreco = new javax.swing.JTextField();
        JbCadastrar = new javax.swing.JButton();
        JbBuscar = new javax.swing.JButton();
        JbExcluir = new javax.swing.JButton();
        JbAlterar = new javax.swing.JButton();
        JtfData = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JProdutos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro de Produtos");

        jLabel2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel2.setText("Nome do Produto:");

        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setText("Preço do Produto:");

        jLabel4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel4.setText("Data de Validade:");

        JtfPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfPrecoActionPerformed(evt);
            }
        });

        JbCadastrar.setBackground(new java.awt.Color(255, 153, 0));
        JbCadastrar.setText("Cadastrar");
        JbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCadastrarActionPerformed(evt);
            }
        });

        JbBuscar.setBackground(new java.awt.Color(255, 153, 0));
        JbBuscar.setText("Buscar");
        JbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbBuscarActionPerformed(evt);
            }
        });

        JbExcluir.setBackground(new java.awt.Color(255, 153, 0));
        JbExcluir.setText("Excluir");
        JbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbExcluirActionPerformed(evt);
            }
        });

        JbAlterar.setBackground(new java.awt.Color(255, 153, 0));
        JbAlterar.setText("Alterar");
        JbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAlterarActionPerformed(evt);
            }
        });

        JtfData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfDataActionPerformed(evt);
            }
        });

        JProdutos.setBackground(new java.awt.Color(255, 153, 0));
        JProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço", "Validade"
            }
        ));
        jScrollPane1.setViewportView(JProdutos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JtfData, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(JtfPreco)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JbCadastrar)
                            .addComponent(JbBuscar))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JbExcluir)
                            .addComponent(JbAlterar))))
                .addContainerGap(70, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JtfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbCadastrar)
                    .addComponent(JbAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbBuscar)
                    .addComponent(JbExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtfPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfPrecoActionPerformed

    private void JtfDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfDataActionPerformed

    private void JbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCadastrarActionPerformed
      try {
            String nomePro = JtfNome.getText();
            double precoPro = Double.parseDouble(JtfPreco.getText());
            String data = JtfData.getText();

            pro.cadastrar(nomePro, data, precoPro);
            JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso");

          atualizarTabela();
            limpar();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Preço inválido. Insira um número válido.");
        }

    }//GEN-LAST:event_JbCadastrarActionPerformed

    private void JbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbBuscarActionPerformed
        nomeBusca = JtfNome.getText();  // Recupera o nome digitado na interface
        Produto produto = pro.buscar(nomeBusca);  // Chama o método de busca

        if (produto == null) {
            JOptionPane.showMessageDialog(null, "Produto não encontrado");
            limpar();  // Limpa os campos se não encontrar
        } else {
            JtfNome.setText(produto.getNome());
            JtfData.setText(produto.getData());
            JtfPreco.setText(String.valueOf(produto.getPreco()));

            // Atualiza a tabela com os dados do produto
            DefaultTableModel modelo = (DefaultTableModel) JProdutos.getModel();
            modelo.setRowCount(0);  // Limpa a tabela antes de adicionar a nova linha
            Object[] dados = { produto.getNome(), produto.getPreco(), produto.getData() };
            modelo.addRow(dados);
        }
    }//GEN-LAST:event_JbBuscarActionPerformed

    private void JbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbExcluirActionPerformed
     nomeBusca = JtfNome.getText();
        if (pro.buscar(nomeBusca) != null) {
            pro.excluir(nomeBusca);
            if (JProdutos.getSelectedRow() != -1) {
                DefaultTableModel Products = (DefaultTableModel) JProdutos.getModel();
                Products.removeRow(JProdutos.getSelectedRow());
            }
            JOptionPane.showMessageDialog(null, "Produto excluído com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Produto não encontrado para exclusão");
        }
        limpar();
    }//GEN-LAST:event_JbExcluirActionPerformed

    private void JbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAlterarActionPerformed
      try {
            String nomeAltera = JtfNome.getText();
            double precoPro = Double.parseDouble(JtfPreco.getText());
            String data = JtfData.getText();

            if (pro.buscar(nomeBusca) != null) {
                pro.alterar(nomeBusca, nomeAltera, data, precoPro);
                JOptionPane.showMessageDialog(null, "Produto alterado com sucesso");

                if (JProdutos.getSelectedRow() != -1) {
                    JProdutos.setValueAt(JtfNome.getText(), JProdutos.getSelectedRow(), 0);
                    JProdutos.setValueAt(JtfPreco.getText(), JProdutos.getSelectedRow(), 1);
                    JProdutos.setValueAt(JtfData.getText(), JProdutos.getSelectedRow(), 2);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Produto não encontrado para alteração");
            }
            limpar();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Preço inválido. Insira um número válido.");
        }

    }//GEN-LAST:event_JbAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JProdutos;
    private javax.swing.JButton JbAlterar;
    private javax.swing.JButton JbBuscar;
    private javax.swing.JButton JbCadastrar;
    private javax.swing.JButton JbExcluir;
    private javax.swing.JTextField JtfData;
    private javax.swing.JTextField JtfNome;
    private javax.swing.JTextField JtfPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void limpar(){
        JtfNome.setText("");
        JtfPreco.setText("");
        JtfData.setText("");
    }
    private void atualizarTabela() {
        // Obter o modelo da tabela
        DefaultTableModel modelo = (DefaultTableModel) JProdutos.getModel();

        // Limpar a tabela antes de adicionar os novos dados
        modelo.setRowCount(0);

        
        }
    }





